version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=course-management-system
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.az
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin-data:
