version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cms-application
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.az
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  course-management-system:
    image: ulviyyalakbarova/course-management-system:v3
    container_name: cms_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRE_URL: postgres
      POSTGRE_PASSWORD: 12345678
      POSTGRE_USERNAME: postgres
    volumes:
      - course-management-system-data:/var/lib/cms

volumes:
  pgdata:
  pgadmin-data:
  course-management-system-data:
